//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strukov
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalBaseEntities2 : DbContext
    {
        public HospitalBaseEntities2()
            : base("name=HospitalBaseEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTHOR> AUTHORs { get; set; }
        public virtual DbSet<CABINET> CABINETs { get; set; }
        public virtual DbSet<GENDER> GENDERs { get; set; }
        public virtual DbSet<NEWS> NEWS { get; set; }
        public virtual DbSet<PRICE> PRICEs { get; set; }
        public virtual DbSet<RECEPTION> RECEPTIONs { get; set; }
        public virtual DbSet<ROLE> ROLEs { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
    }
}
