//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strukov
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEPTION
    {
        public int id { get; set; }
        public Nullable<int> Cabinet { get; set; }
        public Nullable<int> Doctor { get; set; }
        public int Patient { get; set; }
        public System.DateTime RecordingDate { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual CABINET CABINET1 { get; set; }
        public virtual PRICE PRICE1 { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
