//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strukov
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.RECEPTIONs = new HashSet<RECEPTION>();
            this.RECEPTIONs1 = new HashSet<RECEPTION>();
        }
    
        public int id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string MiddleName { get; set; }
        public int RoleId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Region { get; set; }
        public string Siti { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public string Apartament { get; set; }
        public string PhoneNumber { get; set; }
        public string MedicalRecord { get; set; }
        public string Passport { get; set; }
        public int Gender { get; set; }
    
        public virtual GENDER GENDER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEPTION> RECEPTIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEPTION> RECEPTIONs1 { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
